typography_spectrum: 0.6506588
color:
  saturation: 0.2303155
  lightness: 0.3065943
  brandStrength: 0.05275327
  rhythmicContrast: 0.7103917
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.03817851
name: SocialCauses
navigation:
  - name: Home
    id: 38a9ca9e-e101-477e-98d6-3fdcbed9e67e
    type: content
title: SocialCauses
description: Digital solutions for positive social change
